---
name: CGI-IDS
version: 1.00
author:
  - 'Hinnerk Altenburg <hinnerk@cpan.org>'
abstract: "Perl Website Intrusion Detection System (XSS, CSRF, SQLI, LFI etc.)"
license: lgpl
build_requires:
  Carp: 0
  Encode::Unicode: 2.05
  FindBin: 0
  HTML::Entities: 0
  JSON::XS: 2.2222
  MIME::Base64: 0
  Test::More: 0
  Time::HiRes: 0
  XML::Simple: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  CGI::IDS:
    file: lib/CGI/IDS.pm
    version: 1.00
resources:
  license: http://opensource.org/licenses/artistic-license.php
