---
abstract: 'PerlIDS - Perl Website Intrusion Detection System (XSS, CSRF, SQLI, LFI etc.)'
author:
  - 'Hinnerk Altenburg <hinnerk@cpan.org>'
build_requires:
  Carp: 0
  Encode::Unicode: 2.05
  FindBin: 0
  HTML::Entities: 0
  JSON::XS: 2.2
  MIME::Base64: 0
  Test::More: 0
  Time::HiRes: 0
  XML::Parser: 0
  XML::Simple: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: lgpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-IDS
provides:
  CGI::IDS:
    file: lib/CGI/IDS.pm
    version: 1.0118
resources:
  license: http://www.gnu.org/licenses/lgpl-3.0.txt
version: 1.0118
